__default__:
    time: "4:00"
    nCPUS: 8
    memory: 60
    name: "JOBNAME.{rule}.{wildcards}"
    output: "{config[log_dir]}/{rule}.{wildcards}.out"
    error: "{config[log_dir]}/{rule}.{wildcards}.err"
    resources: "\"rusage[mem=10] span[hosts=1]\""

